export { default as schema0 } from "./lib/modules/ContactModule/schema";
export { default as schema1 } from "./lib/modules/HomeAboutMeModule/schema";
export { default as schema2 } from "./lib/modules/HomeCoreInfoModule/schema";
export { default as schema3 } from "./lib/modules/HomeFaqModule/schema";
export { default as schema4 } from "./lib/modules/HomeHighlightModule/schema";
export { default as schema5 } from "./lib/modules/HomeLandingModule/schema";
export { default as schema6 } from "./lib/modules/HomePricingModule/schema";
export { default as schema7 } from "./lib/modules/HomeReviewsModule/schema";
export { default as schema8 } from "./lib/modules/HomeWorkoutsModule/schema";
