export { default as HomeAboutMeModule } from "./HomeAboutMeModule";
export { default as HomeLandingModule } from "./HomeLandingModule";
export { default as HomeCoreInfoModule } from "./HomeCoreInfoModule";
export { default as HomeWorkoutsModule } from "./HomeWorkoutsModule";
export { default as HomeHighlightModule } from "./HomeHighlightModule";
export { default as HomeReviewsModule } from "./HomeReviewsModule";
export { default as HomePricingModule } from "./HomePricingModule";
export { default as HomeFaqModule } from "./HomeFaqModule";
export { default as ContactModule } from "./ContactModule";
